remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "GaTORS: A Game-Theoretic Tool for Optimal Robot Selection and Design"
description: "Supplemental Material"
show_downloads: false
